# .github/workflows/report_gen.yml
name: Weekly Report Generator
on:
  push:
  schedule:
    # every monday at 3AM UTC (9AM Bangladesh Standard Time)
    - cron: "0 3 * * MON"
env:
  RUN_REPOSITORY: action-rest-repo
  ISSUE_REPOSITORY: rpt_arnob-karmokar-primesilicon
  REPORT_BRANCH: weekly-report
  ISSUE_REPO_OWNER: primesilicon
  NAME: "Arnob Karmokar"
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Generate Markdown Report from GitHub Issues
      run: |
        git switch $REPORT_BRANCH
        mkdir -p reports
        cd ..
        git clone https://github.com/arnob-karmokar-primesilicon/github-issue-to-markdown-report
        cd github-issue-to-markdown-report
        pip3 install --user --upgrade setuptools
        pip3 install --user -r requirements.txt
        python3 main.py $ISSUE_REPO_OWNER $ISSUE_REPOSITORY "$NAME" ${{ secrets.PAT_TOKEN }} # python3 main.py <repo-owner> <repository> <Your Name> <TOKEN>
        mkdir reports
        cp -r output/* ../$RUN_REPOSITORY/reports/
    - name: Commit new report file
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Automated weekly report generation by GitHub Action" 
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.PAT_TOKEN }}
        branch: $REPORT_BRANCH
